server:
  port: 9210

spring:
  servlet:
    multipart:    # spring mvc文件上传
      max-request-size: 10MB
      max-file-size: 1MB

azure:
  storage:
    default-endpoints-protocol: https
    account-name: chetwht
    account-key: ENC(47qpkA/jZZ80BZuBMtPLWsjqzweOJXg/Pp1V93H6O1ybBAfD0Kh0n5fD2hYc2/EbDhImXfcl9Y62kEwL0nY6igyHnjRaXlCEOuTzx8Mi558RPN+5ge7jYr9r5NxFjLBRJadv7SfTM6E=)
    endpoint-suffix: core.windows.net
    container-reference: quickstartcontainer2
    generate-thumbnail: false

